version: 0.4-b{build}
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
before_build:
  - cinst -y redis-64
  - git submodule update --init --recursive
  - "\"C:\\Program Files\\PostgreSQL\\9.3\\bin\\psql.exe\" -c \"CREATE USER ipp UNENCRYPTED PASSWORD 'ipp'\" \"postgresql://postgres:Password12!@localhost\""
  - "\"C:\\Program Files\\PostgreSQL\\9.3\\bin\\psql.exe\" -c \"CREATE DATABASE ipp OWNER ipp\" \"postgresql://postgres:Password12!@localhost\""
build_script:
  - .\gradlew.bat
  - .\gradlew.bat postgresTest
test: off
services:
  - postgresql
